#!/bin/python3

from random import shuffle
min = input("[*]	From:	")
max = input("[*]	Till:	")
arr = []

for i in range(int(min), int(max)):
	arr.append(i)

shuffle(arr)

with open("numbers.txt", "w") as fd:
	for num in arr:
		fd.write(f"{num} ")